web:
  build: .
  volumes:
    - .:/var/www/devdir/
  ports:
    - "80:80"
  links:
   - db
  environment:
    ENVIRONMENT: dev
    DATABASE_HOST: db
    DATABASE_NAME: beaver_contest
    DATABASE_USER: dbuser
    DATABASE_PASSWORD: password
db:
  image: mysql
  ports:
    - "3306:3306"
  environment:
    MYSQL_ROOT_PASSWORD: rootpwd
    MYSQL_USER: dbuser
    MYSQL_PASSWORD: password
    MYSQL_DATABASE: beaver_contest
